package com.v20charactermanager.domain.model

object NameDatabase {

    val maleNames: List<String> = listOf(
        "Achille", "Adalberto", "Adamo", "Adriano", "Agostino", "Alarico", "Alberto", "Alboino",
        "Alessandro", "Alfonso", "Alfredo", "Almerico", "Alvaro", "Ambrogio", "Amerigo", "Amilcare",
        "Anastasio", "Andrea", "Angelo", "Anselmo", "Antonio", "Arcangelo", "Arnaldo", "Arturo",
        "Attilio", "Augusto", "Baldassarre", "Barnaba", "Bartolomeo", "Battista", "Beltramo", "Beniamino",
        "Benito", "Benvenuto", "Bertrando", "Blasco", "Bonaventura", "Bruno", "Caetano", "Calcedonio",
        "Callisto", "Calvino", "Camillo", "Carlo", "Carmelo", "Casimiro", "Cassio", "Celestino",
        "Cesare", "Ciriaco", "Clemente", "Colombo", "Costantino", "Crescenzio", "Cristiano", "Cristoforo",
        "Dagoberto", "Dalmazio", "Damiano", "Danilo", "Dante", "Dario", "Davide", "Demetrio",
        "Desiderio", "Diego", "Dino", "Dionigi", "Domenico", "Doroteo", "Edmondo", "Edoardo",
        "Egidio", "Egidio", "Emanuele", "Emilio", "Ennio", "Enrico", "Enzo", "Erasmo",
        "Ercole", "Ermanno", "Erminio", "Ernesto", "Ettore", "Eugenio", "Eusebio", "Eustachio",
        "Fabiano", "Fabrizio", "Fausto", "Federico", "Felice", "Ferdinando", "Fermo", "Fernando",
        "Fiorenzo", "Flavio", "Filippo", "Fortunato", "Francesco", "Frida", "Gabriele", "Gaetano",
        "Galeazzo", "Gastone", "Gennaro", "Genovese", "Gerardo", "Germano", "Gerolamo", "Giacomo",
        "Giambattista", "Giancarlo", "Gianni", "Gioacchino", "Giocondo", "Giorgio", "Giovanni", "Giuliano",
        "Giulio", "Giuseppe", "Giusto", "Goffredo", "Gonzalo", "Gregorio", "Gualtiero", "Guerrino",
        "Guido", "Guglielmo", "Iacopo", "Ignazio", "Ilario", "Innocenzo", "Ippolito", "Isacco",
        "Isaia", "Isidoro", "Italo", "Ivano", "Lamberto", "Lancillotto", "Landolfo", "Lapo",
        "Lazzaro", "Leandro", "Leonardo", "Leone", "Leopoldo", "Liberato", "Lieto", "Lorenzo",
        "Loriano", "Luca", "Luciano", "Lucio", "Ludovico", "Manfredi", "Manuele", "Marcello",
        "Marco", "Mariano", "Marino", "Mario", "Martino", "Massimiliano", "Matteo", "Mattia",
        "Maurizio", "Melchiorre", "Michelangelo", "Michele", "Mirco", "Napoleone", "Narciso", "Natale",
        "Niccolò", "Nicla", "Nino", "Nori", "Oberdan", "Odone", "Oliviero", "Oreste",
        "Orlando", "Orso", "Ottavio", "Ottone", "Ovidio", "Pacifico", "Paolo", "Paris",
        "Pasquale", "Patrizio", "Pellegrino", "Pericle", "Piero", "Pietro", "Pio", "Placido",
        "Porfirio", "Priamo", "Prospero", "Raffaele", "Raimondo", "Raniero", "Riccardo", "Rinaldo",
        "Rino", "Roberto", "Rodolfo", "Romano", "Romeo", "Romolo", "Rosario", "Ruggero",
        "Salvatore", "Samuele", "Sante", "Santo", "Saul", "Saverio", "Scipione", "Sebastiano",
        "Serena", "Sergio", "Silvestro", "Silvio", "Simeone", "Simone", "Socrate", "Solone",
        "Stanislao", "Stefano", "Tacito", "Teodoro", "Teseo", "Timoteo", "Tiziano", "Tolomeo",
        "Tommaso", "Torquato", "Ubaldo", "Uberto", "Ugo", "Umberto", "Valentino", "Valerio",
        "Varedo", "Vasco", "Vincenzo", "Vittorio", "Vittorio", "Viviano", "Zaccaria", "Zenone",
        "Zeno",
        "Adrian", "Alan", "Albert", "Alexander", "Alfred", "Andrew", "Anthony", "Arthur",
        "Benjamin", "Bernard", "Brian", "Bruce", "Caleb", "Carl", "Charles", "Christian",
        "Christopher", "Clarence", "Claude", "Clifford", "Clyde", "Colin", "Craig", "Dale",
        "Damien", "Daniel", "Darren", "David", "Dean", "Dennis", "Derek", "Donald",
        "Douglas", "Dylan", "Edgar", "Edward", "Edwin", "Elijah", "Eric", "Ernest",
        "Ethan", "Eugene", "Felix", "Francis", "Frank", "Frederick", "Gareth", "Gavin",
        "Geoffrey", "George", "Gerald", "Gilbert", "Gordon", "Graham", "Grant", "Gregory",
        "Harold", "Harry", "Henry", "Herbert", "Howard", "Hugh", "Ian", "Isaac",
        "Jack", "Jacob", "James", "Jamie", "Jared", "Jason", "Jeffrey", "Jeremiah",
        "Jeremy", "Jerome", "Jesse", "Jimmy", "Joel", "John", "Jonathan", "Jordan",
        "Joseph", "Joshua", "Julian", "Justin", "Keith", "Kenneth", "Kevin", "Kyle",
        "Lance", "Lawrence", "Leonard", "Liam", "Lloyd", "Luke", "Marcus", "Mark",
        "Martin", "Mason", "Matthew", "Max", "Michael", "Mickel", "Miles", "Mitchell",
        "Nathan", "Neil", "Nicholas", "Nigel", "Noah", "Norman", "Oliver", "Oscar",
        "Owen", "Patrick", "Paul", "Peter", "Philip", "Quentin", "Ralph", "Randy",
        "Raymond", "Richard", "Robert", "Robin", "Roger", "Roland", "Roman", "Ronald",
        "Roy", "Russell", "Ryan", "Samuel", "Scott", "Sean", "Sebastian", "Seth",
        "Simon", "Spencer", "Stanley", "Stephen", "Steven", "Stuart", "Terence", "Theodore",
        "Thomas", "Timothy", "Travis", "Trevor", "Tristan", "Victor", "Vincent", "Walter",
        "Warren", "Wayne", "William", "Xavier", "Zachary",
        "Aarav", "Arjun", "Dev", "Farid", "Hassan", "Ibrahim", "Javier", "Kai",
        "Levi", "Miguel", "Nico", "Omar", "Rafael", "Santiago", "Tariq", "Valentino",
        "Yusuf", "Zain", "Amir", "Dante", "Enzo", "Kofi", "Liam", "Milo",
        "Otto", "Rocco", "Soren", "Theo", "Viktor", "Wolf"
    )

    val femaleNames: List<String> = listOf(
        "Adelaide", "Adriana", "Agata", "Agnese", "Alberta", "Albina", "Alessandra", "Alexandra",
        "Alida", "Alina", "Allegra", "Amalia", "Amanda", "Ambra", "Amelia", "Anna",
        "Annalisa", "Annunziata", "Antonella", "Antonia", "Aquilina", "Arabella", "Arcangela", "Arianna",
        "Armida", "Augusta", "Aurelia", "Azzurra", "Beatrice", "Benedetta", "Beniamina", "Bianca",
        "Brigida", "Brunilda", "Camilla", "Candida", "Capitolina", "Carla", "Carmela", "Carolina",
        "Cassandra", "Caterina", "Catia", "Cecilia", "Celestina", "Chiara", "Cinzia", "Clara",
        "Claudia", "Clementina", "Clotilde", "Concetta", "Consuelo", "Coralia", "Cordelia", "Cornelia",
        "Cristiana", "Cristina", "Dafne", "Dalila", "Daniela", "Daria", "Deborah", "Delfina",
        "Diana", "Diletta", "Dina", "Domenica", "Donatella", "Dorotea", "Edith", "Elena",
        "Eleonora", "Elisa", "Elisabetta", "Ella", "Elsa", "Elvira", "Emilia", "Emily",
        "Emma", "Enrica", "Erica", "Erika", "Erminia", "Ernesta", "Eugenia", "Eva",
        "Evangelina", "Fabiana", "Fabiola", "Fatima", "Federica", "Fernanda", "Fiammetta", "Filippa",
        "Flaminia", "Flora", "Florence", "Fortunata", "Francesca", "Gabriella", "Gaia", "Gelsomina",
        "Genoveffa", "Gentile", "Germana", "Giada", "Gianna", "Giorgia", "Giovanna", "Giulia",
        "Giuliana", "Giulietta", "Giuseppina", "Graziella", "Greta", "Griselda", "Ida", "Ilena",
        "Illuminata", "Immacolata", "India", "Iolanda", "Irene", "Irma", "Isabella", "Isa",
        "Janet", "Jennifer", "Jessica", "Jolanda", "Julia", "Karen", "Katia", "Laura",
        "Lea", "Leda", "Leonora", "Letizia", "Lidia", "Liliana", "Lisa", "Livia",
        "Loretta", "Lucrezia", "Ludovica", "Luisa", "Luna", "Lydia", "Maddalena", "Manuela",
        "Marcella", "Margherita", "Maria", "Mariana", "Marina", "Marisa", "Marta", "Martina",
        "Marzia", "Matilde", "Melania", "Melissa", "Michela", "Milena", "Miranda", "Miriam",
        "Monica", "Nadia", "Natalia", "Nella", "Nicole", "Nicoletta", "Nina", "Noemi",
        "Olga", "Olivia", "Olimpia", "Oriana", "Ornella", "Paola", "Patrizia", "Penelope",
        "Perla", "Petra", "Pierina", "Pina", "Porzia", "Priscilla", "Rachele", "Raffaella",
        "Raimonda", "Rebecca", "Renata", "Ricciarda", "Rita", "Roberta", "Romana", "Rosa",
        "Rosalia", "Rosalinda", "Rossana", "Rossella", "Ruby", "Sabrina", "Sandra", "Sara",
        "Serena", "Silvia", "Simona", "Sofia", "Sonya", "Stefania", "Sylvia", "Tamara",
        "Tania", "Tatiana", "Teresa", "Tina", "Tiziana", "Tommasina", "Torquata", "Valentina",
        "Valeria", "Vanessa", "Vanna", "Velia", "Venezia", "Veronica", "Vilma", "Vincenza",
        "Violetta", "Virginia", "Viviana", "Vittoria", "Zara", "Zoe",
        "Abigail", "Alice", "Amber", "Amy", "Angela", "Ann", "Ashley", "Barbara",
        "Beth", "Beverly", "Bridget", "Brooke", "Candy", "Carol", "Catherine", "Charlotte",
        "Chloe", "Cindy", "Claire", "Colette", "Courtney", "Daisy", "Dana", "Debra",
        "Diana", "Diane", "Donna", "Doris", "Dorothy", "Elizabeth", "Ella", "Emily",
        "Emma", "Erin", "Evelyn", "Fiona", "Florence", "Frances", "Gail", "Gloria",
        "Grace", "Gwen", "Hannah", "Harriet", "Heather", "Helen", "Hope", "Irene",
        "Iris", "Ivy", "Jackie", "Jane", "Janet", "Jasmine", "Jean", "Jennifer",
        "Jessica", "Jill", "Joan", "Jody", "Jordan", "Joy", "Judith", "Julia",
        "Julie", "Karen", "Katherine", "Kathleen", "Kayla", "Kelly", "Kim", "Lacey",
        "Laura", "Lauren", "Linda", "Lisa", "Lucy", "Lydia", "Mabel", "Madeline",
        "Maggie", "Mandy", "Margaret", "Maria", "Marie", "Marilyn", "Martha", "Mary",
        "Megan", "Melanie", "Melinda", "Melissa", "Michelle", "Mildred", "Mirabel", "Molly",
        "Nancy", "Naomi", "Natalie", "Nicole", "Nina", "Olivia", "Pamela", "Patricia",
        "Paula", "Peggy", "Penny", "Phoebe", "Priscilla", "Rachel", "Rebecca", "Regina",
        "Renee", "Rhonda", "Rita", "Roberta", "Rose", "Ruby", "Ruth", "Sally",
        "Samantha", "Sandra", "Sandy", "Sarah", "Scarlett", "Serena", "Sharon", "Sheila",
        "Shelly", "Shirley", "Sophia", "Stacy", "Stephanie", "Susan", "Suzanne", "Sylvia",
        "Teresa", "Tiffany", "Tina", "Tracy", "Valerie", "Vanessa", "Veronica", "Victoria",
        "Violet", "Virginia", "Vivian", "Wanda", "Wendy", "Whitney", "Yvonne", "Zelda",
        "Aisha", "Amara", "Amira", "Anaya", "Aria", "Aurora", "Azalea", "Bella",
        "Bianca", "Camila", "Carmen", "Celeste", "Celine", "Dahlia", "Demi", "Destiny",
        "Eliana", "Elise", "Eloise", "Esme", "Estrella", "Evangeline", "Everly", "Freya",
        "Gabrielle", "Gia", "Gianna", "Giselle", "Harmony", "Harper", "Hazel", "Iris",
        "Isla", "Jade", "Jasmine", "Josephine", "Kaia", "Kira", "Lana", "Lara",
        "Leah", "Lena", "Lila", "Lily", "Luna", "Lyra", "Mabel", "Maeve",
        "Mara", "Mariana", "Marina", "Marisol", "Maya", "Mia", "Mila", "Milana",
        "Mira", "Nadia", "Naomi", "Natalia", "Nina", "Noelle", "Nora", "Novella",
        "Odette", "Ophelia", "Paloma", "Parker", "Pearl", "Penelope", "Petra", "Raven",
        "Rhea", "River", "Rosa", "Rosie", "Rowan", "Ruby", "Sage", "Sara",
        "Selene", "Sienna", "Simone", "Sophia", "Stella", "Summer", "Sylvia", "Thea",
        "Valentina", "Valeria", "Vera", "Violet", "Vivienne", "Wren", "Ximena", "Yara",
        "Zara", "Zoe"
    )

    val surnames: List<String> = listOf(
        "Acciai", "Acciaio", "Alderisi", "Alighieri", "Altoviti", "Ammanati", "Arduino",
        "Baglioni", "Barbieri", "Bardi", "Barnaba", "Bartolini", "Battaglia", "Belmonte",
        "Bernardi", "Bianchi", "Bardi", "Bonaccorsi", "Bonaparte", "Boncompagni", "Bonfili",
        "Bonizzi", "Borgia", "Borromeo", "Boselli", "Brunelleschi", "Bucci", "Buondelmonti",
        "Cacciamani", "Caddeo", "Caligari", "Campana", "Cantelmi", "Capelli", "Capponi",
        "Carducci", "Cariati", "Carnesecchi", "Cavalcanti", "Cenci", "Cerretani", "Cesi",
        "Chigi", "Ciolini", "Coppola", "Corsini", "Corsi", "Cosimo", "Craxi",
        "D'Angelo", "D'Avila", "Dalla Rovere", "Dandini", "De Luca", "De Rossi", "Del Carretto",
        "Della Rovere", "Diaz", "Donati", "Doria", "Dorini", "Drago", "Falconieri",
        "Farnese", "Ferrari", "Ferraro", "Ferruzzi", "Filippini", "Finzi", "Fiorentini",
        "Gambino", "Garibaldi", "Gentile", "Gerini", "Ghetti", "Giannini", "Giordano",
        "Giuliani", "Gondoni", "Gonzaga", "Goria", "Grassi", "Grillo", "Grosoli",
        "Guadagni", "Guarini", "Guicciardini", "Guidi", "Lami", "Leoni", "Lombardi",
        "Lombardo", "Loredan", "Loria", "Luzzi", "Macchi", "Malaparte", "Mancini",
        "Manetti", "Manfredi", "Manni", "Mansueto", "Marchetti", "Marchi", "Marcucci",
        "Martelli", "Martinelli", "Martini", "Marzocco", "Medici", "Mellini", "Menchi",
        "Merini", "Michelozzi", "Mondadori", "Montanelli", "Montefeltro", "Monti", "Morandi",
        "Morelli", "Moreno", "Morosini", "Nannini", "Neri", "Nerli", "Nesi",
        "Nidiaci", "Orsini", "Padgett", "Pallavicini", "Palumbo", "Panciatichi", "Pandolfini",
        "Panichi", "Paoli", "Papini", "Parenti", "Parri", "Passerini", "Pazzi",
        "Pecci", "Pellegrini", "Peruzzi", "Pesci", "Pazzi", "Piccardi", "Pinelli",
        "Pio", "Pirandello", "Pirelli", "Pisani", "Pistoia", "Pitti", "Pizzicato",
        "Pucci", "Racah", "Raimondi", "Rashidi", "Regoli", "Ricci", "Ricciardi",
        "Rizzo", "Romagnoli", "Romano", "Rosini", "Rossi", "Rossini", "Rota",
        "Rucellai", "Ruffini", "Ruspoli", "Sacchetti", "Salviati", "Salvini", "Santoro",
        "Sanzio", "Savorgnan", "Scali", "Scandinavi", "Scarlatti", "Scellino", "Sforza",
        "Simi", "Sinibaldi", "Soderini", "Solari", "Soranzo", "Spani", "Spano",
        "Strozzi", "Stufa", "Taddei", "Tanagli", "Tarugi", "Tempi", "Tencalla",
        "Terzi", "Tornabuoni", "Torrigiani", "Trinci", "Trivulzio", "Ubaldini", "Ugolini",
        "Valenti", "Valenti", "Valentini", "Varchi", "Velluti", "Venturi", "Vespucci",
        "Vettori", "Viali", "Vidali", "Vieri", "Vigili", "Villa", "Villani",
        "Visconti", "Vitelli", "Viviani", "Volpe", "Zanobi", "Zanardo", "Zannoni",
        "Zeffirelli", "Zetti",
        "Abbott", "Adams", "Allen", "Anderson", "Bailey", "Baker", "Barnes", "Bell",
        "Bennett", "Bishop", "Blake", "Booth", "Bowman", "Brooks", "Brown", "Bryant",
        "Campbell", "Carter", "Chapman", "Clark", "Cole", "Collins", "Cook", "Cooper",
        "Cox", "Davis", "Dawson", "Dixon", "Douglas", "Edwards", "Evans", "Fisher",
        "Fletcher", "Ford", "Fox", "Fraser", "Garcia", "Gardner", "Gibson", "Graham",
        "Grant", "Gray", "Green", "Griffin", "Hall", "Hamilton", "Harris", "Hart",
        "Harvey", "Hayes", "Henderson", "Hill", "Hunt", "Hunter", "Ingram", "Jackson",
        "James", "Jenkins", "Johnson", "Jones", "Jordan", "Kelly", "Kennedy", "King",
        "Knight", "Lawrence", "Lee", "Lewis", "Long", "Lopez", "Marshall", "Martin",
        "Mason", "Mathis", "Maxwell", "McCarthy", "McDonald", "Miller", "Mitchell", "Moore",
        "Morgan", "Morris", "Murray", "Nelson", "Nixon", "Norris", "Oliver", "Palmer",
        "Parker", "Patterson", "Payne", "Perry", "Phillips", "Porter", "Powell", "Price",
        "Raven", "Raymond", "Reed", "Reynolds", "Rice", "Richardson", "Riley", "Robertson",
        "Robinson", "Rodriguez", "Rogers", "Rose", "Ross", "Russell", "Ryan", "Sanders",
        "Scott", "Sergeant", "Sharp", "Shaw", "Simpson", "Smith", "Spencer", "Stanley",
        "Stewart", "Stone", "Sullivan", "Taylor", "Thomas", "Thompson", "Turner", "Walker",
        "Wallace", "Ward", "Warren", "Washington", "Watson", "Watts", "Webb", "Wells",
        "West", "White", "Wilkins", "Williams", "Williamson", "Willis", "Wilson", "Wood",
        "Woods", "Wright", "Young",
        "Ashworth", "Baldwin", "Beaumont", "Blackwood", "Bradshaw", "Bramwell", "Caldwell",
        "Carmichael", "Chamberlain", "Chandler", "Clayton", "Colchester", "Conway", "Cowley",
        "Crawford", "Cromwell", "Dalton", "Davenport", "Dawson", "Deacon", "Drummond",
        "Dudley", "Dunbar", "Dunn", "Ellington", "Fairfax", "Falconer", "Fleming",
        "Forrester", "Gallagher", "Gates", "Gifford", "Gilbert", "Godwin", "Gough",
        "Harrington", "Hawkins", "Hawthorne", "Hemsworth", "Heslop", "Hollis", "Houghton",
        "Ingalls", "Ingram", "Irons", "Ives", "Jennings", "Kensington", "Kerr",
        "Langley", "Latham", "Lavender", "Lawson", "Lazenby", "Lockhart", "Lancaster",
        "Lindley", "Loudon", "Lynch", "Maguire", "Manning", "Marlowe", "McAllister",
        "McBride", "McKay", "McLean", "Meadows", "Mitchell", "Monroe", "Montgomery",
        "Moreno", "Morton", "Nash", "Norton", "Oakley", "Osborne", "Pemberton",
        "Pendleton", "Percival", "Quinn", "Ramsey", "Ravenswood", "Redmond", "Ridley",
        "Salisbury", "Sawyer", "Shepherd", "Sinclair", "Slater", "Somerset", "Spencer",
        "Stratford", "Sutherland", "Swift", "Thornton", "Trent", "Vance", "Vickers",
        "Whitaker", "Whitfield", "Wickham", "Wiggins", "Worthington", "York",
        "Ahlgren", "Andersen", "Bergström", "Björk", "Dahl", "Eklund", "Eriksson",
        "Falk", "Gustafsson", "Holm", "Hansen", "Jensen", "Johansson", "Karlsson",
        "Larsson", "Lindqvist", "Lund", "Malm", "Mikkelsen", "Nielsen", "Nordström",
        "Olsson", "Pedersen", "Pettersson", "Sandberg", "Ström", "Svensson", "Thomsen",
        "Aalderink", "Van Bergen", "De Graaf", "Van Dijk", "Visser", "Smit", "Bakker",
        "Jansen", "De Vries", "Van den Berg", "Brouwer", "De Boer", "Hendriks", "Van der Meer",
        "Bos", "Mulder", "Groot", "Hogenboom", "Kok", "Dijkstra", "Bosman",
        "Weber", "Müller", "Schmidt", "Schneider", "Fischer", "Meyer", "Wagner",
        "Becker", "Schulz", "Hoffmann", "Schäfer", "Koch", "Richter", "Klein",
        "Wolf", "Schröder", "Neumann", "Schwarz", "Zimmermann", "Braun", "Hartmann",
        "Lorenz", "König", "Huber", "Kaiser", "Peters", "Lang", "Fuchs",
        "Keller", "Vogel", "Kowalski", "Schmitz", "Jäger", "Lorenz", "Horn",
        "Bauer", "Richter", "Krause", "Lehmann", "Schmidt", "Müller", "Weber",
        "Dubois", "Moreau", "Laurent", "Simon", "Michel", "Lefevre", "Roux",
        "David", "Bertrand", "Morel", "Girard", "André", "Lefebvre", "Mercier",
        "Dupont", "Lambert", "Bonnet", "François", "Martinez", "Legrand", "Garnier",
        "Chevalier", "Franco", "Romero", "Vargas", "Morales", "Gutierrez", "Ortiz",
        "Ruiz", "Alvarez", "Moreno", "Torres", "Castro", "Velasquez", "Ramos",
        "Fernandez", "Garcia", "Rodriguez", "Lopez", "Hernandez", "Gonzalez", "Perez",
        "Sanchez", "Ramirez", "Torres", "Flores", "Rivera", "Gomez", "Diaz"
    )

    fun getRandomMaleName(): String = maleNames.random()

    fun getRandomFemaleName(): String = femaleNames.random()

    fun getRandomSurname(): String = surnames.random()

    fun getRandomName(gender: Gender?): String {
        return when (gender) {
            Gender.MALE -> getRandomMaleName()
            Gender.FEMALE -> getRandomFemaleName()
            null -> if (kotlin.random.Random.nextBoolean()) getRandomMaleName() else getRandomFemaleName()
        }
    }

    fun getRandomFullName(gender: Gender? = null): Pair<String, String> {
        return getRandomName(gender) to getRandomSurname()
    }
}

enum class Gender {
    MALE, FEMALE
}
